name: Publish react_ui to npmjs
on:
  push:
    branches:
      - test-ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i
      - run: pnpm ui-react:build
      - run: pnpm publish --filter @ui-aurora/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
